/**
 * Scene Lab: simulated sessions for comparing scene harnesses. The learner is a real participant
 * replaying their own lines (reference scenarios) or a learner model (authored scenarios); the cast
 * is generated by the production generator with a harness variant, and deliveries are stored the way
 * the worker stores them. A simulated clock follows the product's timing (reply delays, paced
 * deliveries, a live group chat moving on while the learner types), so sessions can be replayed.
 */

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { env } from "$env/dynamic/private";
import { getLanguageEnglishName, URGENCY_PRESETS } from "$lib/constants";
import { getCommentId } from "$lib/practice/comment-thread";
import { formatMailAddress, formatMailMessage } from "$lib/practice/mail";
import { getDeliveryDelayMs, sampleReplyDelayMs } from "$lib/practice/reply-timing";
import { isLiveChat } from "$lib/practice/scene";
import { db } from "$lib/server/db";
import { task as taskTable } from "$lib/server/db/schema";
import type { ChatOptions } from "$lib/server/llm/client";
import { defineLlmRecipe } from "$lib/server/llm/recipe";
import type { LlmVariant } from "$lib/server/llm/run";
import { runLlmRecipe } from "$lib/server/llm/run";
import { type AgentHistoryMessage, agentTaskContext, generateAgentResponse, type SceneTurn } from "$lib/server/practice/agent-replies/generator";
import { type AgentEvent, buildAgentTranscript, isThreadedUi } from "$lib/server/practice/agent-replies/prompt";
import { buildDeliveredReplyMetadata, LIVE_CHAT_TICKS } from "$lib/server/practice/agent-replies/worker";
import { renderScenarioSetting, renderTaskBrief, type TranscriptEntry } from "$lib/server/practice/prompt-context";
import { loadReference, type ScriptLine } from "./references";
import { SCENARIOS, type Scenario } from "./scenarios";

export const RESULTS_DIR = join(process.cwd(), "tmp", "scene-lab");

/**
 * A harness variant, as an LLM Lab variant of the scene reply recipe: slot overrides, options
 * (reasoning effort, temperature), and another model on the environment's OpenRouter endpoint.
 * An empty variant runs the recipe as declared. The learner always runs on the default model.
 */
/**
 * A harness variant. `improvise`: in reference scenarios the learner writes their own lines instead
 * of replaying the real ones, as a real learner would. `source`: the cast knows how the real
 * conversation went on (only fair with `improvise`, or the cast would know the learner's lines).
 */
export type Variant = {
	key: string;
	label: string;
	slots?: Record<string, string>;
	options?: ChatOptions;
	model?: string;
	improvise?: boolean;
	source?: boolean;
};

export const VARIANTS: Variant[] = [
	{ key: "current", label: "Current harness" },
	{ key: "improvised", label: "Learner improvises", improvise: true },
	{ key: "sourced", label: "Learner improvises, cast knows what really followed", improvise: true, source: true },
];

function labVariant(variant: Variant): LlmVariant | undefined {
	if (!variant.slots && !variant.options && !variant.model) return undefined;
	const provider = variant.model
		? { id: `scene-lab:${variant.model}`, apiKey: env.OPENAI_API_KEY ?? "", baseUrl: env.OPENAI_BASE_URL ?? "", model: variant.model }
		: undefined;
	return { slots: variant.slots, options: variant.options, provider };
}

type LiveTask = Parameters<typeof agentTaskContext>[0];

type LoadedScene = { task: LiveTask; learnerName: string; script: ScriptLine[] | null; referenceText: string | null };

async function loadScene(scenario: Scenario): Promise<LoadedScene> {
	const id = 900_000 + SCENARIOS.indexOf(scenario);
	if (scenario.reference) {
		const { task, learnerName, script, source, referenceText } = await loadReference(scenario.reference);
		return { task: { id, ...task, objectives: null, materialsMd: null, source }, learnerName, script, referenceText };
	}
	if (scenario.task)
		return { task: { id, ...scenario.task, objectives: null, materialsMd: null }, learnerName: "Maple", script: null, referenceText: null };
	const row = await db.query.task.findFirst({ where: eq(taskTable.id, scenario.taskId ?? 0) });
	if (!row) throw new Error(`Task ${scenario.taskId} not found`);
	return { task: { ...row, openingState: row.openingState ?? null }, learnerName: "Maple", script: null, referenceText: null };
}

/** The real conversation behind a reference scenario, for reading beside the simulated ones. */
export async function referenceText(scenarioId: string): Promise<string | null> {
	const scenario = SCENARIOS.find((candidate) => candidate.id === scenarioId);
	return scenario?.reference ? (await loadReference(scenario.reference)).referenceText : null;
}

// ── The simulated learner ─────────────────────────────────────────────

const learnerSchema = z.object({
	replyTo: z.unknown().transform((value) => (typeof value === "number" && Number.isInteger(value) ? value : null)),
	subject: z.string().optional(),
	text: z.string().trim(),
});

/** One learner persona per seed for authored scenarios, so a variant is not tuned to one kind of learner. */
const PERSONAS = [
	"You are talkative and opinionated, and like to argue a little.",
	"You are shy: you write briefly and only when you have something to say.",
	"You are curious and ask people things, sometimes off topic.",
	"You are relaxed and a bit jokey, and do not take the scene too seriously.",
];

type LearnerInput = {
	task: ReturnType<typeof agentTaskContext>;
	learnerName: string;
	transcript: TranscriptEntry[];
	seed: number;
	/** The real participant's next line, in reference scenarios. */
	line: ScriptLine | null;
};

const learnerRecipe = defineLlmRecipe({
	id: "scene-lab.learner",
	version: 2,
	title: "Scene Lab learner",
	reasoningEffort: "low",
	output: { kind: "json", schema: learnerSchema },
	options: { temperature: 1 },
	build: (input: LearnerInput) => {
		const { task, line } = input;
		const language = getLanguageEnglishName(task.language);
		const target = isThreadedUi(task.ui) ? "id of the entry you answer, or null for a new top-level comment" : "null";
		const role = line
			? [
					`You are ${input.learnerName}, a real participant of this ${task.ui} conversation, replaying what you actually wrote.`,
					`Your next real message was:\n«${line.text}»${line.answering ? `\nIt answered ${line.answering.author}: «${line.answering.text}»` : ""}`,
					"- Post that message again, keeping its wording, spelling, length and tone. Change only what no longer makes sense because the others here said different things; never polish it.",
					"- replyTo: the entry here that best matches what you answered.",
				]
			: [
					`You are ${input.learnerName}, an intermediate (B1) learner of ${language} whose native language is Chinese, using a ${task.ui} interface in a practice scenario. You write as yourself, in ${language}. ${PERSONAS[input.seed % PERSONAS.length]}`,
					"- Write like a real person on this platform, with the mistakes typical of your level (articles, prepositions, tense, word choice, a missing word), and plain vocabulary.",
					"- Pursue your goal, but react to what people actually say. Never repeat or sum up what you already said, and do not thank or praise people every time. If a question got a vague answer or none, do not ask it again: take what you got or move on.",
					"- Usually one to three sentences; mail is longer. Emoji only rarely.",
					"- Once your goal is met, join whatever people are discussing with your own view, or stay silent by returning empty text.",
					`## YOUR TASK\n${renderTaskBrief(task)}`,
				];
		return [
			{
				role: "system",
				content: [
					...role,
					`## SETTING\n${renderScenarioSetting(task.ui, task.openingState, task.scene)}`,
					`Return only JSON: {"replyTo": ${target}, ${task.ui === "apple_mail" ? '"subject": "…", ' : ""}"text": "your message"}`,
				].join("\n\n"),
			},
			{ role: "user", content: JSON.stringify({ transcript: input.transcript }, null, 1) },
		];
	},
});

// ── Simulation ────────────────────────────────────────────────────────

export type SimTurn = {
	event: AgentEvent | { kind: "learner" };
	learner?: { replyTo: number | null; text: string };
	scene?: Pick<SceneTurn, "decision" | "deliveries" | "warnings">;
	/** Simulated time (ms from the start): when the learner sent, or when the first delivery landed. */
	at?: number;
	latencyMs: number;
	error?: string;
};

export type SimResult = {
	id: string;
	scenarioId: string;
	/** Whether others besides the counterpart can speak. */
	group: boolean;
	variant: string;
	seed: number;
	startedAt: string;
	finishedAt?: string;
	turns: SimTurn[];
	transcript: TranscriptEntry[];
};

/** Deterministic randomness for the simulated clock. */
function clockRandom(seed: number) {
	let state = seed * 2654435761 + 1;
	return () => (state = (state * 1103515245 + 12345) >>> 0) / 4294967296;
}

/** How long the learner takes to read, think and type a message of this length. */
function learnerDelayMs(length: number, random: () => number) {
	return 20_000 + random() * 40_000 + Math.min(120_000, (length / 2.5) * 1000);
}

export async function simulate(
	scenario: Scenario,
	variant: Variant,
	seed: number,
	onProgress: (result: SimResult) => Promise<void>,
): Promise<SimResult> {
	const loaded = await loadScene(scenario);
	const { learnerName } = loaded;
	const liveTask = { ...loaded.task, source: variant.source ? loaded.task.source : null };
	const script = variant.improvise ? null : loaded.script;
	const task = agentTaskContext(liveTask, learnerName);
	const history: AgentHistoryMessage[] = [];
	let nextMessageId = 1;
	const result: SimResult = {
		id: `${scenario.id}__${variant.key}__${seed}`,
		scenarioId: scenario.id,
		group: task.scene.group,
		variant: variant.key,
		seed,
		startedAt: new Date().toISOString(),
		turns: [],
		transcript: [],
	};
	const transcript = () => buildAgentTranscript({ task, history, learnerName });
	const random = clockRandom(seed + 1);
	const live = isLiveChat(task.ui, task.scene);
	const urgency = ((liveTask as { urgency?: string }).urgency ?? "high") as "high";
	// When the learner can act again: the last delivery has landed.
	let clock = 0;
	// Follow-ups so far (a live chat's budget restarts whenever the cast answers the learner), and
	// whether the last turn left anyone likely to post again.
	let idles = 0;
	let lively = true;
	// As in the worker, a terminated scene takes no more turns.
	let ended = false;

	/** One cast turn, landing `delay` after `from`; returns whether it produced messages. */
	const castTurn = async (event: AgentEvent, from: number, delay: number) => {
		const started = performance.now();
		try {
			const generated = await generateAgentResponse({
				task: liveTask,
				learnerName,
				history,
				event,
				variant: labVariant(variant),
				seed: seed * 1000 + result.turns.length,
			});
			const latencyMs = Math.round(performance.now() - started);
			const { decision, deliveries, warnings, allowIdleFollowUp } = generated.parsedResult;
			ended ||= decision === "terminate_abuse";
			lively = allowIdleFollowUp && !ended;
			if (event.kind === "reply" && live) idles = 0;
			const at = from + delay + latencyMs;
			const delivered: string[] = [];
			let landed = at;
			for (const [index, delivery] of deliveries.entries()) {
				if (index > 0) landed += getDeliveryDelayMs(delivery.content);
				const replyTo = delivery.replyTo?.startsWith("@") ? (delivered[Number(delivery.replyTo.slice(1))] ?? null) : delivery.replyTo;
				const id = nextMessageId++;
				history.push({
					id,
					role: "assistant",
					content: delivery.content,
					llmMetadata: buildDeliveredReplyMetadata(task.ui, { author: delivery.author, replyTo }, null),
				});
				delivered.push(getCommentId(task.ui, { id: String(id), role: "agent" }));
			}
			result.turns.push({ event, scene: { decision, deliveries, warnings }, at, latencyMs });
			clock = Math.max(clock, landed);
		} catch (error) {
			result.turns.push({ event, latencyMs: Math.round(performance.now() - started), error: error instanceof Error ? error.message : String(error) });
		}
		result.transcript = transcript().entries;
		await onProgress(result);
	};
	const timePasses = (from: number, delay: number) => castTurn({ kind: "follow_up", followUpCount: ++idles }, from, delay);
	const tickDelay = () => 60_000 + random() * 60_000;

	const lines = script ? Math.min(script.length, 5) : 5;
	for (let turn = 0; turn < lines; turn += 1) {
		const line = script?.[turn] ?? null;
		const sendAt = clock + learnerDelayMs(line?.text.length ?? 70, random);
		// A live group chat moves on while the learner reads and types.
		for (let tick = clock + tickDelay(); live && lively && idles < LIVE_CHAT_TICKS && tick < sendAt; tick = clock + tickDelay())
			await timePasses(tick, 0);
		if (ended) break;
		const started = performance.now();
		try {
			const { entries, refs } = transcript();
			const input = { task, learnerName, transcript: entries, seed, line };
			// The provider now and then returns nothing; one retry keeps a session from ending early.
			const { value } = await runLlmRecipe(learnerRecipe, input).catch(() => runLlmRecipe(learnerRecipe, input));
			if (value.text) {
				const clientMessageId = `sim${nextMessageId}`;
				const target = value.replyTo && value.replyTo <= refs.length ? refs[value.replyTo - 1] : null;
				const lastSubject = (task.openingState?.emails as Array<{ subject?: string }> | undefined)?.at(-1)?.subject ?? "";
				const content =
					task.ui === "apple_mail"
						? formatMailMessage({
								to: task.scene.cast.map(formatMailAddress).join(", "),
								subject: value.subject ?? `Re: ${lastSubject}`,
								body: value.text,
							})
						: value.text;
				history.push({
					id: nextMessageId++,
					role: "user",
					content,
					llmMetadata: {
						clientMessageId,
						...(isThreadedUi(task.ui) ? { thread: { commentId: `${task.ui}-user-${clientMessageId}`, targetCommentId: target } } : {}),
					},
				});
				result.turns.push({
					event: { kind: "learner" },
					learner: { replyTo: value.replyTo, text: value.text },
					at: Math.max(sendAt, clock),
					latencyMs: Math.round(performance.now() - started),
				});
				await castTurn({ kind: "reply" }, Math.max(sendAt, clock), sampleReplyDelayMs(urgency, random));
			} else if (!live) await timePasses(clock, URGENCY_PRESETS[urgency].idleFollowUpDelayMs);
		} catch (error) {
			result.turns.push({ event: { kind: "learner" }, latencyMs: 0, error: String(error) });
			break;
		}
		// Elsewhere, the quiet periods of the old schedule: after the learner's second and fourth turns.
		if (!live && lively && (turn === 1 || turn === 3) && idles < 2) await timePasses(clock, URGENCY_PRESETS[urgency].idleFollowUpDelayMs);
	}
	// A live chat carries on for a while after the learner's last message.
	for (let count = 0; live && lively && count < 2 && idles < LIVE_CHAT_TICKS; count += 1) await timePasses(clock, tickDelay());
	result.finishedAt = new Date().toISOString();
	await onProgress(result);
	return result;
}

// ── Runs and storage ──────────────────────────────────────────────────

export async function saveResult(runId: string, result: SimResult) {
	const dir = join(RESULTS_DIR, runId);
	await mkdir(dir, { recursive: true });
	await writeFile(join(dir, `${result.id}.json`), JSON.stringify(result, null, 1));
}

export async function listRuns(): Promise<string[]> {
	try {
		return (await readdir(RESULTS_DIR)).sort().reverse();
	} catch {
		return [];
	}
}

export async function loadRun(runId: string): Promise<SimResult[]> {
	const dir = join(RESULTS_DIR, runId);
	const files = (await readdir(dir)).filter((file) => file.endsWith(".json"));
	return Promise.all(files.map(async (file) => JSON.parse(await readFile(join(dir, file), "utf8")) as SimResult));
}

/** Runs every scenario × variant × seed with bounded concurrency. */
export async function startRun(input: { scenarios: string[]; variants: string[]; seeds: number; concurrency?: number }): Promise<string> {
	const runId = new Date().toISOString().replace(/[:.]/g, "-");
	const queue = SCENARIOS.filter((scenario) => input.scenarios.includes(scenario.id)).flatMap((scenario) =>
		VARIANTS.filter((variant) => input.variants.includes(variant.key)).flatMap((variant) =>
			Array.from({ length: input.seeds }, (_, seed) => ({ scenario, variant, seed })),
		),
	);
	const worker = async () => {
		for (let job = queue.shift(); job; job = queue.shift()) {
			const { scenario, variant, seed } = job;
			await simulate(scenario, variant, seed, (result) => saveResult(runId, result)).catch((error) =>
				console.error(`[scene-lab] ${scenario.id}/${variant.key}/${seed} failed`, error),
			);
		}
	};
	void Promise.all(Array.from({ length: input.concurrency ?? 6 }, worker)).then(() => console.log(`[scene-lab] run ${runId} simulated`));
	return runId;
}
